[package]
name = "gdesktop_enums"
version = "0.0.1"
edition = "2018"

[lib]
name = "gdesktop_enums"

[dependencies]
bitflags = "1.3.2"
ffi = { package = "gdesktop_enums-sys", path = "../gdesktop_enums-sys" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core" }
libc = "0.2.100"
