[workspace]
members = [
    "clutter",
    "clutter-sys",
    "cogl",
    "cogl-sys",
    "gdesktop_enums",
    "gdesktop_enums-sys",
    "json-sys",
    "meta",
    "meta-sys",
    "xlib-sys",
]
exclude = [
    "gir",
]
