[options]
library = "Meta"
version = "8"
target_path = "."
work_mode = "normal"

generate = [
	"Meta.Background",
	"Meta.BackgroundActor",
	"Meta.BackgroundContent",
	"Meta.BackgroundGroup",
	"Meta.Cursor",
	"Meta.DisplayCorner",
	"Meta.DisplayDirection",
	"Meta.FrameType",
	"Meta.GrabOp",
	"Meta.KeyBinding",
	"Meta.KeyBindingFlags",
	"Meta.MaximizeFlags",
	"Meta.ModalOptions",
	"Meta.MotionDirection",
	"Meta.PadActionType",
	"Meta.Plugin",
	"Meta.Rectangle",
	"Meta.Selection",
	"Meta.SelectionSource",
	"Meta.SelectionType",
	"Meta.StackLayer",
	"Meta.TabList",
	"Meta.WindowClientType",
	"Meta.WindowType",
	"Meta.Workspace",
	"Meta.WorkspaceManager",
]

manual = [
	"cairo.RectangleInt",
	"cairo.Region",
	"cairo.Surface",
	"Clutter.Actor",
	"Clutter.Content",
	"Clutter.InputDevice",
	"GDesktopEnums.BackgroundStyle",
	"GLib.Error",
	"Gio.Cancellable",
	"Gio.File",
	"Gio.InputStream",
	"Gio.OutputStream",
	"Gio.Settings",
	"Gio.Task",
	"GObject.Object",
]

[[object]]
name = "Meta.Display"
status = "generate"
	[[object.function]]
	name = "sort_windows_by_stacking"
	ignore = true

[[object]]
name = "Meta.Window"
status = "generate"
	[[object.function]]
	name = "set_icon_geometry"
	ignore = true

[[object]]
name = "Meta.WindowActor"
status = "generate"
	[[object.function]]
	name = "get_image"
	ignore = true
