// Generated by gir (https://github.com/gtk-rs/gir @ 45cd7bc)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

mod enums;
pub use self::enums::BackgroundStyle;

#[doc(hidden)]
pub mod traits {
}
