// Generated by gir (https://github.com/gtk-rs/gir @ b193568)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

use crate::ActorMeta;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "ClutterAction")]
    pub struct Action(Object<ffi::ClutterAction, ffi::ClutterActionClass>) @extends ActorMeta;

    match fn {
        type_ => || ffi::clutter_action_get_type(),
    }
}

impl Action {}

pub const NONE_ACTION: Option<&Action> = None;

impl fmt::Display for Action {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Action")
    }
}
