// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

mod actor;
pub use self::actor::{Actor, NONE_ACTOR};

mod content;
pub use self::content::{Content, NONE_CONTENT};

mod input_device;
pub use self::input_device::{InputDevice};

mod enums;
#[cfg(any(feature = "v1_6", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v1_6")))]
pub use self::enums::StaticColor;

#[doc(hidden)]
pub mod traits {
    pub use super::actor::ActorExt;
    pub use super::content::ContentExt;
}
