// Generated by gir (https://github.com/gtk-rs/gir @ 45cd7bc)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

mod backend;
pub use self::backend::{Backend};

mod background;
pub use self::background::{Background};

mod background_actor;
pub use self::background_actor::{BackgroundActor};

mod background_content;
pub use self::background_content::{BackgroundContent};

mod background_group;
pub use self::background_group::{BackgroundGroup, NONE_BACKGROUND_GROUP};

mod compositor;
pub use self::compositor::{Compositor};

mod display;
pub use self::display::{Display};

mod monitor_manager;
pub use self::monitor_manager::{MonitorManager};

mod plugin;
pub use self::plugin::{Plugin, NONE_PLUGIN};

mod selection;
pub use self::selection::{Selection};

mod selection_source;
pub use self::selection_source::{SelectionSource, NONE_SELECTION_SOURCE};

mod stage;
pub use self::stage::{Stage};

mod window;
pub use self::window::{Window};

mod window_actor;
pub use self::window_actor::{WindowActor};

mod window_group;
pub use self::window_group::{WindowGroup};

mod workspace;
pub use self::workspace::{Workspace};

mod workspace_manager;
pub use self::workspace_manager::{WorkspaceManager};

mod key_binding;
pub use self::key_binding::KeyBinding;

mod rectangle;
pub use self::rectangle::Rectangle;

mod enums;
pub use self::enums::Cursor;
pub use self::enums::DisplayCorner;
pub use self::enums::DisplayDirection;
pub use self::enums::ExitCode;
pub use self::enums::FrameType;
pub use self::enums::GrabOp;
pub use self::enums::MotionDirection;
pub use self::enums::PadActionType;
pub use self::enums::SelectionType;
pub use self::enums::StackLayer;
pub use self::enums::TabList;
pub use self::enums::WindowClientType;
pub use self::enums::WindowType;

mod flags;
pub use self::flags::Direction;
pub use self::flags::KeyBindingFlags;
pub use self::flags::MaximizeFlags;
pub use self::flags::ModalOptions;

pub mod functions;

#[doc(hidden)]
pub mod traits {
    pub use super::plugin::PluginExt;
    pub use super::selection_source::SelectionSourceExt;
}
