// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT(JSON_MAJOR_VERSION);
    PRINT_CONSTANT(JSON_MICRO_VERSION);
    PRINT_CONSTANT(JSON_MINOR_VERSION);
    PRINT_CONSTANT((gint) JSON_NODE_ARRAY);
    PRINT_CONSTANT((gint) JSON_NODE_NULL);
    PRINT_CONSTANT((gint) JSON_NODE_OBJECT);
    PRINT_CONSTANT((gint) JSON_NODE_VALUE);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_EMPTY_MEMBER_NAME);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_INVALID_BAREWORD);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_INVALID_DATA);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_MISSING_COLON);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_MISSING_COMMA);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_PARSE);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_TRAILING_COMMA);
    PRINT_CONSTANT((gint) JSON_PARSER_ERROR_UNKNOWN);
    PRINT_CONSTANT((gint) JSON_PATH_ERROR_INVALID_QUERY);
    PRINT_CONSTANT((gint) JSON_READER_ERROR_INVALID_INDEX);
    PRINT_CONSTANT((gint) JSON_READER_ERROR_INVALID_MEMBER);
    PRINT_CONSTANT((gint) JSON_READER_ERROR_INVALID_NODE);
    PRINT_CONSTANT((gint) JSON_READER_ERROR_INVALID_TYPE);
    PRINT_CONSTANT((gint) JSON_READER_ERROR_NO_ARRAY);
    PRINT_CONSTANT((gint) JSON_READER_ERROR_NO_OBJECT);
    PRINT_CONSTANT((gint) JSON_READER_ERROR_NO_VALUE);
    PRINT_CONSTANT(JSON_VERSION_S);
    return 0;
}
