// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "JsonBuilder", sizeof(JsonBuilder), alignof(JsonBuilder));
    printf("%s;%zu;%zu\n", "JsonBuilderClass", sizeof(JsonBuilderClass), alignof(JsonBuilderClass));
    printf("%s;%zu;%zu\n", "JsonGenerator", sizeof(JsonGenerator), alignof(JsonGenerator));
    printf("%s;%zu;%zu\n", "JsonGeneratorClass", sizeof(JsonGeneratorClass), alignof(JsonGeneratorClass));
    printf("%s;%zu;%zu\n", "JsonNodeType", sizeof(JsonNodeType), alignof(JsonNodeType));
    printf("%s;%zu;%zu\n", "JsonObjectIter", sizeof(JsonObjectIter), alignof(JsonObjectIter));
    printf("%s;%zu;%zu\n", "JsonParser", sizeof(JsonParser), alignof(JsonParser));
    printf("%s;%zu;%zu\n", "JsonParserClass", sizeof(JsonParserClass), alignof(JsonParserClass));
    printf("%s;%zu;%zu\n", "JsonParserError", sizeof(JsonParserError), alignof(JsonParserError));
    printf("%s;%zu;%zu\n", "JsonPathError", sizeof(JsonPathError), alignof(JsonPathError));
    printf("%s;%zu;%zu\n", "JsonReader", sizeof(JsonReader), alignof(JsonReader));
    printf("%s;%zu;%zu\n", "JsonReaderClass", sizeof(JsonReaderClass), alignof(JsonReaderClass));
    printf("%s;%zu;%zu\n", "JsonReaderError", sizeof(JsonReaderError), alignof(JsonReaderError));
    printf("%s;%zu;%zu\n", "JsonSerializableIface", sizeof(JsonSerializableIface), alignof(JsonSerializableIface));
    return 0;
}
