// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "MetaBackend", sizeof(MetaBackend), alignof(MetaBackend));
    printf("%s;%zu;%zu\n", "MetaBackgroundActorClass", sizeof(MetaBackgroundActorClass), alignof(MetaBackgroundActorClass));
    printf("%s;%zu;%zu\n", "MetaBackgroundClass", sizeof(MetaBackgroundClass), alignof(MetaBackgroundClass));
    printf("%s;%zu;%zu\n", "MetaBackgroundContentClass", sizeof(MetaBackgroundContentClass), alignof(MetaBackgroundContentClass));
    printf("%s;%zu;%zu\n", "MetaBackgroundGroup", sizeof(MetaBackgroundGroup), alignof(MetaBackgroundGroup));
    printf("%s;%zu;%zu\n", "MetaBackgroundGroupClass", sizeof(MetaBackgroundGroupClass), alignof(MetaBackgroundGroupClass));
    printf("%s;%zu;%zu\n", "MetaBackgroundImageCacheClass", sizeof(MetaBackgroundImageCacheClass), alignof(MetaBackgroundImageCacheClass));
    printf("%s;%zu;%zu\n", "MetaBackgroundImageClass", sizeof(MetaBackgroundImageClass), alignof(MetaBackgroundImageClass));
    printf("%s;%zu;%zu\n", "MetaBarrier", sizeof(MetaBarrier), alignof(MetaBarrier));
    printf("%s;%zu;%zu\n", "MetaBarrierClass", sizeof(MetaBarrierClass), alignof(MetaBarrierClass));
    printf("%s;%zu;%zu\n", "MetaBarrierDirection", sizeof(MetaBarrierDirection), alignof(MetaBarrierDirection));
    printf("%s;%zu;%zu\n", "MetaBarrierEvent", sizeof(MetaBarrierEvent), alignof(MetaBarrierEvent));
    printf("%s;%zu;%zu\n", "MetaButtonFunction", sizeof(MetaButtonFunction), alignof(MetaButtonFunction));
    printf("%s;%zu;%zu\n", "MetaButtonLayout", sizeof(MetaButtonLayout), alignof(MetaButtonLayout));
    printf("%s;%zu;%zu\n", "MetaCloseDialogInterface", sizeof(MetaCloseDialogInterface), alignof(MetaCloseDialogInterface));
    printf("%s;%zu;%zu\n", "MetaCloseDialogResponse", sizeof(MetaCloseDialogResponse), alignof(MetaCloseDialogResponse));
    printf("%s;%zu;%zu\n", "MetaCompEffect", sizeof(MetaCompEffect), alignof(MetaCompEffect));
    printf("%s;%zu;%zu\n", "MetaCompositor", sizeof(MetaCompositor), alignof(MetaCompositor));
    printf("%s;%zu;%zu\n", "MetaCursor", sizeof(MetaCursor), alignof(MetaCursor));
    printf("%s;%zu;%zu\n", "MetaCursorTracker", sizeof(MetaCursorTracker), alignof(MetaCursorTracker));
    printf("%s;%zu;%zu\n", "MetaDebugPaintFlag", sizeof(MetaDebugPaintFlag), alignof(MetaDebugPaintFlag));
    printf("%s;%zu;%zu\n", "MetaDebugTopic", sizeof(MetaDebugTopic), alignof(MetaDebugTopic));
    printf("%s;%zu;%zu\n", "MetaDirection", sizeof(MetaDirection), alignof(MetaDirection));
    printf("%s;%zu;%zu\n", "MetaDisplayCorner", sizeof(MetaDisplayCorner), alignof(MetaDisplayCorner));
    printf("%s;%zu;%zu\n", "MetaDisplayDirection", sizeof(MetaDisplayDirection), alignof(MetaDisplayDirection));
    printf("%s;%zu;%zu\n", "MetaDndClass", sizeof(MetaDndClass), alignof(MetaDndClass));
    printf("%s;%zu;%zu\n", "MetaEdge", sizeof(MetaEdge), alignof(MetaEdge));
    printf("%s;%zu;%zu\n", "MetaEdgeType", sizeof(MetaEdgeType), alignof(MetaEdgeType));
    printf("%s;%zu;%zu\n", "MetaExitCode", sizeof(MetaExitCode), alignof(MetaExitCode));
    printf("%s;%zu;%zu\n", "MetaFrameBorders", sizeof(MetaFrameBorders), alignof(MetaFrameBorders));
    printf("%s;%zu;%zu\n", "MetaFrameFlags", sizeof(MetaFrameFlags), alignof(MetaFrameFlags));
    printf("%s;%zu;%zu\n", "MetaFrameType", sizeof(MetaFrameType), alignof(MetaFrameType));
    printf("%s;%zu;%zu\n", "MetaGrabOp", sizeof(MetaGrabOp), alignof(MetaGrabOp));
    printf("%s;%zu;%zu\n", "MetaGravity", sizeof(MetaGravity), alignof(MetaGravity));
    printf("%s;%zu;%zu\n", "MetaInhibitShortcutsDialogInterface", sizeof(MetaInhibitShortcutsDialogInterface), alignof(MetaInhibitShortcutsDialogInterface));
    printf("%s;%zu;%zu\n", "MetaInhibitShortcutsDialogResponse", sizeof(MetaInhibitShortcutsDialogResponse), alignof(MetaInhibitShortcutsDialogResponse));
    printf("%s;%zu;%zu\n", "MetaKeyBindingAction", sizeof(MetaKeyBindingAction), alignof(MetaKeyBindingAction));
    printf("%s;%zu;%zu\n", "MetaKeyBindingFlags", sizeof(MetaKeyBindingFlags), alignof(MetaKeyBindingFlags));
    printf("%s;%zu;%zu\n", "MetaLaterType", sizeof(MetaLaterType), alignof(MetaLaterType));
    printf("%s;%zu;%zu\n", "MetaLaunchContextClass", sizeof(MetaLaunchContextClass), alignof(MetaLaunchContextClass));
    printf("%s;%zu;%zu\n", "MetaLocaleDirection", sizeof(MetaLocaleDirection), alignof(MetaLocaleDirection));
    printf("%s;%zu;%zu\n", "MetaMaximizeFlags", sizeof(MetaMaximizeFlags), alignof(MetaMaximizeFlags));
    printf("%s;%zu;%zu\n", "MetaModalOptions", sizeof(MetaModalOptions), alignof(MetaModalOptions));
    printf("%s;%zu;%zu\n", "MetaMonitorSwitchConfigType", sizeof(MetaMonitorSwitchConfigType), alignof(MetaMonitorSwitchConfigType));
    printf("%s;%zu;%zu\n", "MetaMotionDirection", sizeof(MetaMotionDirection), alignof(MetaMotionDirection));
    printf("%s;%zu;%zu\n", "MetaPadActionType", sizeof(MetaPadActionType), alignof(MetaPadActionType));
    printf("%s;%zu;%zu\n", "MetaPlugin", sizeof(MetaPlugin), alignof(MetaPlugin));
    printf("%s;%zu;%zu\n", "MetaPluginClass", sizeof(MetaPluginClass), alignof(MetaPluginClass));
    printf("%s;%zu;%zu\n", "MetaPluginInfo", sizeof(MetaPluginInfo), alignof(MetaPluginInfo));
    printf("%s;%zu;%zu\n", "MetaPreference", sizeof(MetaPreference), alignof(MetaPreference));
    printf("%s;%zu;%zu\n", "MetaRectangle", sizeof(MetaRectangle), alignof(MetaRectangle));
    printf("%s;%zu;%zu\n", "MetaRemoteAccessControllerClass", sizeof(MetaRemoteAccessControllerClass), alignof(MetaRemoteAccessControllerClass));
    printf("%s;%zu;%zu\n", "MetaRemoteAccessHandle", sizeof(MetaRemoteAccessHandle), alignof(MetaRemoteAccessHandle));
    printf("%s;%zu;%zu\n", "MetaRemoteAccessHandleClass", sizeof(MetaRemoteAccessHandleClass), alignof(MetaRemoteAccessHandleClass));
    printf("%s;%zu;%zu\n", "MetaSelectionClass", sizeof(MetaSelectionClass), alignof(MetaSelectionClass));
    printf("%s;%zu;%zu\n", "MetaSelectionSource", sizeof(MetaSelectionSource), alignof(MetaSelectionSource));
    printf("%s;%zu;%zu\n", "MetaSelectionSourceClass", sizeof(MetaSelectionSourceClass), alignof(MetaSelectionSourceClass));
    printf("%s;%zu;%zu\n", "MetaSelectionSourceMemoryClass", sizeof(MetaSelectionSourceMemoryClass), alignof(MetaSelectionSourceMemoryClass));
    printf("%s;%zu;%zu\n", "MetaSelectionType", sizeof(MetaSelectionType), alignof(MetaSelectionType));
    printf("%s;%zu;%zu\n", "MetaShadowFactoryClass", sizeof(MetaShadowFactoryClass), alignof(MetaShadowFactoryClass));
    printf("%s;%zu;%zu\n", "MetaShadowMode", sizeof(MetaShadowMode), alignof(MetaShadowMode));
    printf("%s;%zu;%zu\n", "MetaShadowParams", sizeof(MetaShadowParams), alignof(MetaShadowParams));
    printf("%s;%zu;%zu\n", "MetaShapedTextureClass", sizeof(MetaShapedTextureClass), alignof(MetaShapedTextureClass));
    printf("%s;%zu;%zu\n", "MetaSide", sizeof(MetaSide), alignof(MetaSide));
    printf("%s;%zu;%zu\n", "MetaSizeChange", sizeof(MetaSizeChange), alignof(MetaSizeChange));
    printf("%s;%zu;%zu\n", "MetaSoundPlayerClass", sizeof(MetaSoundPlayerClass), alignof(MetaSoundPlayerClass));
    printf("%s;%zu;%zu\n", "MetaStackLayer", sizeof(MetaStackLayer), alignof(MetaStackLayer));
    printf("%s;%zu;%zu\n", "MetaStageClass", sizeof(MetaStageClass), alignof(MetaStageClass));
    printf("%s;%zu;%zu\n", "MetaStartupNotificationClass", sizeof(MetaStartupNotificationClass), alignof(MetaStartupNotificationClass));
    printf("%s;%zu;%zu\n", "MetaStartupSequence", sizeof(MetaStartupSequence), alignof(MetaStartupSequence));
    printf("%s;%zu;%zu\n", "MetaStrut", sizeof(MetaStrut), alignof(MetaStrut));
    printf("%s;%zu;%zu\n", "MetaTabList", sizeof(MetaTabList), alignof(MetaTabList));
    printf("%s;%zu;%zu\n", "MetaTabShowType", sizeof(MetaTabShowType), alignof(MetaTabShowType));
    printf("%s;%zu;%zu\n", "MetaVirtualModifier", sizeof(MetaVirtualModifier), alignof(MetaVirtualModifier));
    printf("%s;%zu;%zu\n", "MetaWaylandClientClass", sizeof(MetaWaylandClientClass), alignof(MetaWaylandClientClass));
    printf("%s;%zu;%zu\n", "MetaWindowActor", sizeof(MetaWindowActor), alignof(MetaWindowActor));
    printf("%s;%zu;%zu\n", "MetaWindowClientType", sizeof(MetaWindowClientType), alignof(MetaWindowClientType));
    printf("%s;%zu;%zu\n", "MetaWindowGroupClass", sizeof(MetaWindowGroupClass), alignof(MetaWindowGroupClass));
    printf("%s;%zu;%zu\n", "MetaWindowMenuType", sizeof(MetaWindowMenuType), alignof(MetaWindowMenuType));
    printf("%s;%zu;%zu\n", "MetaWindowType", sizeof(MetaWindowType), alignof(MetaWindowType));
    printf("%s;%zu;%zu\n", "MetaWorkspaceManagerClass", sizeof(MetaWorkspaceManagerClass), alignof(MetaWorkspaceManagerClass));
    printf("%s;%zu;%zu\n", "MetaX11DisplayClass", sizeof(MetaX11DisplayClass), alignof(MetaX11DisplayClass));
    return 0;
}
