// Generated by gir (https://github.com/gtk-rs/gir @ 45cd7bc)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

mod texture;
pub use self::texture::{Texture, NONE_TEXTURE};

mod flags;
#[cfg(any(feature = "v0_8", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v0_8")))]
pub use self::flags::PixelFormat;

pub mod functions;

#[doc(hidden)]
pub mod traits {
    pub use super::texture::TextureExt;
}
