// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GDesktopBackgroundShading", sizeof(GDesktopBackgroundShading), alignof(GDesktopBackgroundShading));
    printf("%s;%zu;%zu\n", "GDesktopBackgroundStyle", sizeof(GDesktopBackgroundStyle), alignof(GDesktopBackgroundStyle));
    printf("%s;%zu;%zu\n", "GDesktopClockFormat", sizeof(GDesktopClockFormat), alignof(GDesktopClockFormat));
    printf("%s;%zu;%zu\n", "GDesktopDeviceSendEvents", sizeof(GDesktopDeviceSendEvents), alignof(GDesktopDeviceSendEvents));
    printf("%s;%zu;%zu\n", "GDesktopFocusMode", sizeof(GDesktopFocusMode), alignof(GDesktopFocusMode));
    printf("%s;%zu;%zu\n", "GDesktopFocusNewWindows", sizeof(GDesktopFocusNewWindows), alignof(GDesktopFocusNewWindows));
    printf("%s;%zu;%zu\n", "GDesktopFontAntialiasingMode", sizeof(GDesktopFontAntialiasingMode), alignof(GDesktopFontAntialiasingMode));
    printf("%s;%zu;%zu\n", "GDesktopFontHinting", sizeof(GDesktopFontHinting), alignof(GDesktopFontHinting));
    printf("%s;%zu;%zu\n", "GDesktopFontRgbaOrder", sizeof(GDesktopFontRgbaOrder), alignof(GDesktopFontRgbaOrder));
    printf("%s;%zu;%zu\n", "GDesktopLocationAccuracyLevel", sizeof(GDesktopLocationAccuracyLevel), alignof(GDesktopLocationAccuracyLevel));
    printf("%s;%zu;%zu\n", "GDesktopMagnifierCaretTrackingMode", sizeof(GDesktopMagnifierCaretTrackingMode), alignof(GDesktopMagnifierCaretTrackingMode));
    printf("%s;%zu;%zu\n", "GDesktopMagnifierFocusTrackingMode", sizeof(GDesktopMagnifierFocusTrackingMode), alignof(GDesktopMagnifierFocusTrackingMode));
    printf("%s;%zu;%zu\n", "GDesktopMagnifierMouseTrackingMode", sizeof(GDesktopMagnifierMouseTrackingMode), alignof(GDesktopMagnifierMouseTrackingMode));
    printf("%s;%zu;%zu\n", "GDesktopMagnifierScreenPosition", sizeof(GDesktopMagnifierScreenPosition), alignof(GDesktopMagnifierScreenPosition));
    printf("%s;%zu;%zu\n", "GDesktopMouseDwellDirection", sizeof(GDesktopMouseDwellDirection), alignof(GDesktopMouseDwellDirection));
    printf("%s;%zu;%zu\n", "GDesktopMouseDwellMode", sizeof(GDesktopMouseDwellMode), alignof(GDesktopMouseDwellMode));
    printf("%s;%zu;%zu\n", "GDesktopPadButtonAction", sizeof(GDesktopPadButtonAction), alignof(GDesktopPadButtonAction));
    printf("%s;%zu;%zu\n", "GDesktopPointerAccelProfile", sizeof(GDesktopPointerAccelProfile), alignof(GDesktopPointerAccelProfile));
    printf("%s;%zu;%zu\n", "GDesktopProxyMode", sizeof(GDesktopProxyMode), alignof(GDesktopProxyMode));
    printf("%s;%zu;%zu\n", "GDesktopScreensaverMode", sizeof(GDesktopScreensaverMode), alignof(GDesktopScreensaverMode));
    printf("%s;%zu;%zu\n", "GDesktopStylusButtonAction", sizeof(GDesktopStylusButtonAction), alignof(GDesktopStylusButtonAction));
    printf("%s;%zu;%zu\n", "GDesktopTabletMapping", sizeof(GDesktopTabletMapping), alignof(GDesktopTabletMapping));
    printf("%s;%zu;%zu\n", "GDesktopTitlebarAction", sizeof(GDesktopTitlebarAction), alignof(GDesktopTitlebarAction));
    printf("%s;%zu;%zu\n", "GDesktopToolbarIconSize", sizeof(GDesktopToolbarIconSize), alignof(GDesktopToolbarIconSize));
    printf("%s;%zu;%zu\n", "GDesktopToolbarStyle", sizeof(GDesktopToolbarStyle), alignof(GDesktopToolbarStyle));
    printf("%s;%zu;%zu\n", "GDesktopTouchpadClickMethod", sizeof(GDesktopTouchpadClickMethod), alignof(GDesktopTouchpadClickMethod));
    printf("%s;%zu;%zu\n", "GDesktopTouchpadHandedness", sizeof(GDesktopTouchpadHandedness), alignof(GDesktopTouchpadHandedness));
    printf("%s;%zu;%zu\n", "GDesktopTouchpadTapButtonMap", sizeof(GDesktopTouchpadTapButtonMap), alignof(GDesktopTouchpadTapButtonMap));
    printf("%s;%zu;%zu\n", "GDesktopUsbProtection", sizeof(GDesktopUsbProtection), alignof(GDesktopUsbProtection));
    printf("%s;%zu;%zu\n", "GDesktopVisualBellType", sizeof(GDesktopVisualBellType), alignof(GDesktopVisualBellType));
    return 0;
}
