[options]
library = "Clutter"
version = "8"
target_path = "."
work_mode = "normal"

generate = [
	"Clutter.Actor",
	"Clutter.Content",
	"Clutter.InputDevice",
	"Clutter.StaticColor",
]

[[object]]
name = "Clutter.Color"
status = "generate"
	[[object.function]]
	name = "equal"
	ignore = true
	[[object.function]]
	name = "hash"
	ignore = true

[[object]]
name = "Clutter.Stage"
status = "generate"
	[[object.function]]
	name = "read_pixels"
	ignore = true
