[options]
library = "Clutter"
version = "8"
target_path = "."
work_mode = "normal"

generate = [
	"Clutter.Actor",
	#"Clutter.Color",
	"Clutter.Content",
	"Clutter.InputDevice",
	"Clutter.StaticColor",
]
