[options]
library = "Clutter"
version = "8"
target_path = "."
work_mode = "normal"

generate = [
	"Clutter.Action",
	"Clutter.Actor",
	"Clutter.ActorAlign",
	"Clutter.ActorFlags",
	"Clutter.ActorMeta",
	"Clutter.AlignAxis",
	"Clutter.AlignConstraint",
	"Clutter.Animatable",
	"Clutter.AnimationMode",
	"Clutter.Backend",
	"Clutter.Canvas",
	"Clutter.Constraint",
	"Clutter.Container",
	"Clutter.Content",
	"Clutter.ContentGravity",
	"Clutter.Effect",
	"Clutter.EventFlags",
	"Clutter.EventType",
	"Clutter.Image",
	"Clutter.InputDevice",
	"Clutter.InputFocus",
	"Clutter.InputMethod",
	"Clutter.ModifierType",
	"Clutter.Orientation",
	"Clutter.RequestMode",
	"Clutter.ScalingFilter",
	"Clutter.Scriptable",
	"Clutter.StaticColor",
	"Clutter.Text",
	"Clutter.TextDirection",
]

manual = [
	"cairo.Context",
	"cairo.FontOptions",
	"cairo.RectangleInt",
	"Clutter.KeyEvent",
	"Cogl.PixelFormat",
	"Cogl.Texture",
	"GLib.Bytes",
	"GLib.DestroyNotify",
	"GLib.Error",
	"GLib.SourceFunc",
	"Pango.Alignment",
	"Pango.AttrList",
	"Pango.Context",
	"Pango.EllipsizeMode",
	"Pango.FontDescription",
	"Pango.FontMap",
	"Pango.Layout",
	"Pango.WrapMode",
]

[[object]]
name = "Clutter.*"
status = "generate"
	[[object.constant]]
	pattern = "*"
	ignore = true
	[[object.function]]
	name = "cairo_clear"
	ignore = true
	[[object.function]]
	name = "cairo_set_source_color"
	ignore = true

[[object]]
name = "Clutter.Color"
status = "generate"
	[[object.function]]
	name = "equal"
	ignore = true
	[[object.function]]
	name = "hash"
	ignore = true

[[object]]
name = "Clutter.Stage"
status = "generate"
	[[object.function]]
	name = "capture_into"
	ignore = true
	[[object.function]]
	name = "read_pixels"
	ignore = true

[[object]]
name = "Clutter.TextBuffer"
status = "generate"
	[[object.function]]
	name = "new_with_text"
	ignore = true
