[options]
library = "Clutter"
version = "8"
target_path = "."
work_mode = "normal"

generate = [
	"Clutter.Action",
	"Clutter.Actor",
	"Clutter.ActorAlign",
	"Clutter.ActorFlags",
	"Clutter.ActorMeta",
	"Clutter.Animatable",
	"Clutter.AnimationMode",
	"Clutter.Backend",
	"Clutter.Constraint",
	"Clutter.Container",
	"Clutter.Content",
	"Clutter.EventFlags",
	"Clutter.EventType",
	"Clutter.InputDevice",
	"Clutter.InputFocus",
	"Clutter.InputMethod",
	"Clutter.ModifierType",
	"Clutter.Scriptable",
	"Clutter.StaticColor",
	"Clutter.Text",
]

manual = [
	"Clutter.KeyEvent",
	"GLib.DestroyNotify",
	"GLib.Error",
	"GLib.SourceFunc",
]

[[object]]
name = "Clutter.*"
status = "generate"
	[[object.constant]]
	pattern = "*"
	ignore = true

[[object]]
name = "Clutter.Color"
status = "generate"
	[[object.function]]
	name = "equal"
	ignore = true
	[[object.function]]
	name = "hash"
	ignore = true

[[object]]
name = "Clutter.Stage"
status = "generate"
	[[object.function]]
	name = "read_pixels"
	ignore = true

[[object]]
name = "Clutter.TextBuffer"
status = "generate"
	[[object.function]]
	name = "new_with_text"
	ignore = true
