// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "CoglAngle", sizeof(CoglAngle), alignof(CoglAngle));
    printf("%s;%zu;%zu\n", "CoglAttributeType", sizeof(CoglAttributeType), alignof(CoglAttributeType));
    printf("%s;%zu;%zu\n", "CoglBitmapError", sizeof(CoglBitmapError), alignof(CoglBitmapError));
    printf("%s;%zu;%zu\n", "CoglBlendStringError", sizeof(CoglBlendStringError), alignof(CoglBlendStringError));
    printf("%s;%zu;%zu\n", "CoglBufferBit", sizeof(CoglBufferBit), alignof(CoglBufferBit));
    printf("%s;%zu;%zu\n", "CoglBufferTarget", sizeof(CoglBufferTarget), alignof(CoglBufferTarget));
    printf("%s;%zu;%zu\n", "CoglColor", sizeof(CoglColor), alignof(CoglColor));
    printf("%s;%zu;%zu\n", "CoglDebugObjectTypeInfo", sizeof(CoglDebugObjectTypeInfo), alignof(CoglDebugObjectTypeInfo));
    printf("%s;%zu;%zu\n", "CoglDepthTestFunction", sizeof(CoglDepthTestFunction), alignof(CoglDepthTestFunction));
    printf("%s;%zu;%zu\n", "CoglEglImageFlags", sizeof(CoglEglImageFlags), alignof(CoglEglImageFlags));
    printf("%s;%zu;%zu\n", "CoglFeatureID", sizeof(CoglFeatureID), alignof(CoglFeatureID));
    printf("%s;%zu;%zu\n", "CoglFilterReturn", sizeof(CoglFilterReturn), alignof(CoglFilterReturn));
    printf("%s;%zu;%zu\n", "CoglFrameEvent", sizeof(CoglFrameEvent), alignof(CoglFrameEvent));
    printf("%s;%zu;%zu\n", "CoglFramebuffer", sizeof(CoglFramebuffer), alignof(CoglFramebuffer));
    printf("%s;%zu;%zu\n", "CoglFramebufferClass", sizeof(CoglFramebufferClass), alignof(CoglFramebufferClass));
    printf("%s;%zu;%zu\n", "CoglFramebufferError", sizeof(CoglFramebufferError), alignof(CoglFramebufferError));
    printf("%s;%zu;%zu\n", "CoglGraphicsResetStatus", sizeof(CoglGraphicsResetStatus), alignof(CoglGraphicsResetStatus));
    printf("%s;%zu;%zu\n", "CoglHandle", sizeof(CoglHandle), alignof(CoglHandle));
    printf("%s;%zu;%zu\n", "CoglIndicesType", sizeof(CoglIndicesType), alignof(CoglIndicesType));
    printf("%s;%zu;%zu\n", "CoglMaterialAlphaFunc", sizeof(CoglMaterialAlphaFunc), alignof(CoglMaterialAlphaFunc));
    printf("%s;%zu;%zu\n", "CoglMaterialFilter", sizeof(CoglMaterialFilter), alignof(CoglMaterialFilter));
    printf("%s;%zu;%zu\n", "CoglMaterialWrapMode", sizeof(CoglMaterialWrapMode), alignof(CoglMaterialWrapMode));
    printf("%s;%zu;%zu\n", "CoglOffscreenClass", sizeof(CoglOffscreenClass), alignof(CoglOffscreenClass));
    printf("%s;%zu;%zu\n", "CoglOnscreen", sizeof(CoglOnscreen), alignof(CoglOnscreen));
    printf("%s;%zu;%zu\n", "CoglOnscreenClass", sizeof(CoglOnscreenClass), alignof(CoglOnscreenClass));
    printf("%s;%zu;%zu\n", "CoglOnscreenDirtyInfo", sizeof(CoglOnscreenDirtyInfo), alignof(CoglOnscreenDirtyInfo));
    printf("%s;%zu;%zu\n", "CoglPipelineAlphaFunc", sizeof(CoglPipelineAlphaFunc), alignof(CoglPipelineAlphaFunc));
    printf("%s;%zu;%zu\n", "CoglPipelineCullFaceMode", sizeof(CoglPipelineCullFaceMode), alignof(CoglPipelineCullFaceMode));
    printf("%s;%zu;%zu\n", "CoglPipelineFilter", sizeof(CoglPipelineFilter), alignof(CoglPipelineFilter));
    printf("%s;%zu;%zu\n", "CoglPipelineKey", sizeof(CoglPipelineKey), alignof(CoglPipelineKey));
    printf("%s;%zu;%zu\n", "CoglPipelineWrapMode", sizeof(CoglPipelineWrapMode), alignof(CoglPipelineWrapMode));
    printf("%s;%zu;%zu\n", "CoglPixelFormat", sizeof(CoglPixelFormat), alignof(CoglPixelFormat));
    printf("%s;%zu;%zu\n", "CoglReadPixelsFlags", sizeof(CoglReadPixelsFlags), alignof(CoglReadPixelsFlags));
    printf("%s;%zu;%zu\n", "CoglRendererError", sizeof(CoglRendererError), alignof(CoglRendererError));
    printf("%s;%zu;%zu\n", "CoglScanoutError", sizeof(CoglScanoutError), alignof(CoglScanoutError));
    printf("%s;%zu;%zu\n", "CoglShaderType", sizeof(CoglShaderType), alignof(CoglShaderType));
    printf("%s;%zu;%zu\n", "CoglStereoMode", sizeof(CoglStereoMode), alignof(CoglStereoMode));
    printf("%s;%zu;%zu\n", "CoglSystemError", sizeof(CoglSystemError), alignof(CoglSystemError));
    printf("%s;%zu;%zu\n", "CoglTextureComponents", sizeof(CoglTextureComponents), alignof(CoglTextureComponents));
    printf("%s;%zu;%zu\n", "CoglTextureError", sizeof(CoglTextureError), alignof(CoglTextureError));
    printf("%s;%zu;%zu\n", "CoglTextureFlags", sizeof(CoglTextureFlags), alignof(CoglTextureFlags));
    printf("%s;%zu;%zu\n", "CoglTextureVertex", sizeof(CoglTextureVertex), alignof(CoglTextureVertex));
    printf("%s;%zu;%zu\n", "CoglTraceHead", sizeof(CoglTraceHead), alignof(CoglTraceHead));
    printf("%s;%zu;%zu\n", "CoglUserDataDestroyCallback", sizeof(CoglUserDataDestroyCallback), alignof(CoglUserDataDestroyCallback));
    printf("%s;%zu;%zu\n", "CoglUserDataKey", sizeof(CoglUserDataKey), alignof(CoglUserDataKey));
    printf("%s;%zu;%zu\n", "CoglVerticesMode", sizeof(CoglVerticesMode), alignof(CoglVerticesMode));
    printf("%s;%zu;%zu\n", "CoglWinding", sizeof(CoglWinding), alignof(CoglWinding));
    printf("%s;%zu;%zu\n", "CoglWinsysFeature", sizeof(CoglWinsysFeature), alignof(CoglWinsysFeature));
    return 0;
}
