// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
#![allow(clippy::approx_constant, clippy::type_complexity, clippy::unreadable_literal, clippy::upper_case_acronyms)]
#![cfg_attr(feature = "dox", feature(doc_cfg))]

use glib_sys as glib;

#[allow(unused_imports)]
use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong,
    c_void, size_t, ssize_t, intptr_t, uintptr_t, time_t, FILE};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

// Enums
pub type GDesktopBackgroundShading = c_int;
pub const G_DESKTOP_BACKGROUND_SHADING_SOLID: GDesktopBackgroundShading = 0;
pub const G_DESKTOP_BACKGROUND_SHADING_VERTICAL: GDesktopBackgroundShading = 1;
pub const G_DESKTOP_BACKGROUND_SHADING_HORIZONTAL: GDesktopBackgroundShading = 2;

pub type GDesktopBackgroundStyle = c_int;
pub const G_DESKTOP_BACKGROUND_STYLE_NONE: GDesktopBackgroundStyle = 0;
pub const G_DESKTOP_BACKGROUND_STYLE_WALLPAPER: GDesktopBackgroundStyle = 1;
pub const G_DESKTOP_BACKGROUND_STYLE_CENTERED: GDesktopBackgroundStyle = 2;
pub const G_DESKTOP_BACKGROUND_STYLE_SCALED: GDesktopBackgroundStyle = 3;
pub const G_DESKTOP_BACKGROUND_STYLE_STRETCHED: GDesktopBackgroundStyle = 4;
pub const G_DESKTOP_BACKGROUND_STYLE_ZOOM: GDesktopBackgroundStyle = 5;
pub const G_DESKTOP_BACKGROUND_STYLE_SPANNED: GDesktopBackgroundStyle = 6;

pub type GDesktopClockFormat = c_int;
pub const G_DESKTOP_CLOCK_FORMAT_24H: GDesktopClockFormat = 0;
pub const G_DESKTOP_CLOCK_FORMAT_12H: GDesktopClockFormat = 1;

pub type GDesktopDeviceSendEvents = c_int;
pub const G_DESKTOP_DEVICE_SEND_EVENTS_ENABLED: GDesktopDeviceSendEvents = 0;
pub const G_DESKTOP_DEVICE_SEND_EVENTS_DISABLED: GDesktopDeviceSendEvents = 1;
pub const G_DESKTOP_DEVICE_SEND_EVENTS_DISABLED_ON_EXTERNAL_MOUSE: GDesktopDeviceSendEvents = 2;

pub type GDesktopFocusMode = c_int;
pub const G_DESKTOP_FOCUS_MODE_CLICK: GDesktopFocusMode = 0;
pub const G_DESKTOP_FOCUS_MODE_SLOPPY: GDesktopFocusMode = 1;
pub const G_DESKTOP_FOCUS_MODE_MOUSE: GDesktopFocusMode = 2;

pub type GDesktopFocusNewWindows = c_int;
pub const G_DESKTOP_FOCUS_NEW_WINDOWS_SMART: GDesktopFocusNewWindows = 0;
pub const G_DESKTOP_FOCUS_NEW_WINDOWS_STRICT: GDesktopFocusNewWindows = 1;

pub type GDesktopFontAntialiasingMode = c_int;
pub const G_DESKTOP_FONT_ANTIALIASING_MODE_NONE: GDesktopFontAntialiasingMode = 0;
pub const G_DESKTOP_FONT_ANTIALIASING_MODE_GRAYSCALE: GDesktopFontAntialiasingMode = 1;
pub const G_DESKTOP_FONT_ANTIALIASING_MODE_RGBA: GDesktopFontAntialiasingMode = 2;

pub type GDesktopFontHinting = c_int;
pub const G_DESKTOP_FONT_HINTING_NONE: GDesktopFontHinting = 0;
pub const G_DESKTOP_FONT_HINTING_SLIGHT: GDesktopFontHinting = 1;
pub const G_DESKTOP_FONT_HINTING_MEDIUM: GDesktopFontHinting = 2;
pub const G_DESKTOP_FONT_HINTING_FULL: GDesktopFontHinting = 3;

pub type GDesktopFontRgbaOrder = c_int;
pub const G_DESKTOP_FONT_RGBA_ORDER_RGBA: GDesktopFontRgbaOrder = 0;
pub const G_DESKTOP_FONT_RGBA_ORDER_RGB: GDesktopFontRgbaOrder = 1;
pub const G_DESKTOP_FONT_RGBA_ORDER_BGR: GDesktopFontRgbaOrder = 2;
pub const G_DESKTOP_FONT_RGBA_ORDER_VRGB: GDesktopFontRgbaOrder = 3;
pub const G_DESKTOP_FONT_RGBA_ORDER_VBGR: GDesktopFontRgbaOrder = 4;

pub type GDesktopLocationAccuracyLevel = c_int;
pub const G_DESKTOP_LOCATION_ACCURACY_LEVEL_COUNTRY: GDesktopLocationAccuracyLevel = 0;
pub const G_DESKTOP_LOCATION_ACCURACY_LEVEL_CITY: GDesktopLocationAccuracyLevel = 1;
pub const G_DESKTOP_LOCATION_ACCURACY_LEVEL_NEIGHBORHOOD: GDesktopLocationAccuracyLevel = 2;
pub const G_DESKTOP_LOCATION_ACCURACY_LEVEL_STREET: GDesktopLocationAccuracyLevel = 3;
pub const G_DESKTOP_LOCATION_ACCURACY_LEVEL_EXACT: GDesktopLocationAccuracyLevel = 4;

pub type GDesktopMagnifierCaretTrackingMode = c_int;
pub const G_DESKTOP_MAGNIFIER_CARET_TRACKING_MODE_NONE: GDesktopMagnifierCaretTrackingMode = 0;
pub const G_DESKTOP_MAGNIFIER_CARET_TRACKING_MODE_CENTERED: GDesktopMagnifierCaretTrackingMode = 1;
pub const G_DESKTOP_MAGNIFIER_CARET_TRACKING_MODE_PROPORTIONAL: GDesktopMagnifierCaretTrackingMode = 2;
pub const G_DESKTOP_MAGNIFIER_CARET_TRACKING_MODE_PUSH: GDesktopMagnifierCaretTrackingMode = 3;

pub type GDesktopMagnifierFocusTrackingMode = c_int;
pub const G_DESKTOP_MAGNIFIER_FOCUS_TRACKING_MODE_NONE: GDesktopMagnifierFocusTrackingMode = 0;
pub const G_DESKTOP_MAGNIFIER_FOCUS_TRACKING_MODE_CENTERED: GDesktopMagnifierFocusTrackingMode = 1;
pub const G_DESKTOP_MAGNIFIER_FOCUS_TRACKING_MODE_PROPORTIONAL: GDesktopMagnifierFocusTrackingMode = 2;
pub const G_DESKTOP_MAGNIFIER_FOCUS_TRACKING_MODE_PUSH: GDesktopMagnifierFocusTrackingMode = 3;

pub type GDesktopMagnifierMouseTrackingMode = c_int;
pub const G_DESKTOP_MAGNIFIER_MOUSE_TRACKING_MODE_NONE: GDesktopMagnifierMouseTrackingMode = 0;
pub const G_DESKTOP_MAGNIFIER_MOUSE_TRACKING_MODE_CENTERED: GDesktopMagnifierMouseTrackingMode = 1;
pub const G_DESKTOP_MAGNIFIER_MOUSE_TRACKING_MODE_PROPORTIONAL: GDesktopMagnifierMouseTrackingMode = 2;
pub const G_DESKTOP_MAGNIFIER_MOUSE_TRACKING_MODE_PUSH: GDesktopMagnifierMouseTrackingMode = 3;

pub type GDesktopMagnifierScreenPosition = c_int;
pub const G_DESKTOP_MAGNIFIER_SCREEN_POSITION_NONE: GDesktopMagnifierScreenPosition = 0;
pub const G_DESKTOP_MAGNIFIER_SCREEN_POSITION_FULL_SCREEN: GDesktopMagnifierScreenPosition = 1;
pub const G_DESKTOP_MAGNIFIER_SCREEN_POSITION_TOP_HALF: GDesktopMagnifierScreenPosition = 2;
pub const G_DESKTOP_MAGNIFIER_SCREEN_POSITION_BOTTOM_HALF: GDesktopMagnifierScreenPosition = 3;
pub const G_DESKTOP_MAGNIFIER_SCREEN_POSITION_LEFT_HALF: GDesktopMagnifierScreenPosition = 4;
pub const G_DESKTOP_MAGNIFIER_SCREEN_POSITION_RIGHT_HALF: GDesktopMagnifierScreenPosition = 5;

pub type GDesktopMouseDwellDirection = c_int;
pub const G_DESKTOP_MOUSE_DWELL_DIRECTION_LEFT: GDesktopMouseDwellDirection = 0;
pub const G_DESKTOP_MOUSE_DWELL_DIRECTION_RIGHT: GDesktopMouseDwellDirection = 1;
pub const G_DESKTOP_MOUSE_DWELL_DIRECTION_UP: GDesktopMouseDwellDirection = 2;
pub const G_DESKTOP_MOUSE_DWELL_DIRECTION_DOWN: GDesktopMouseDwellDirection = 3;

pub type GDesktopMouseDwellMode = c_int;
pub const G_DESKTOP_MOUSE_DWELL_MODE_WINDOW: GDesktopMouseDwellMode = 0;
pub const G_DESKTOP_MOUSE_DWELL_MODE_GESTURE: GDesktopMouseDwellMode = 1;

pub type GDesktopPadButtonAction = c_int;
pub const G_DESKTOP_PAD_BUTTON_ACTION_NONE: GDesktopPadButtonAction = 0;
pub const G_DESKTOP_PAD_BUTTON_ACTION_HELP: GDesktopPadButtonAction = 1;
pub const G_DESKTOP_PAD_BUTTON_ACTION_SWITCH_MONITOR: GDesktopPadButtonAction = 2;
pub const G_DESKTOP_PAD_BUTTON_ACTION_KEYBINDING: GDesktopPadButtonAction = 3;

pub type GDesktopPointerAccelProfile = c_int;
pub const G_DESKTOP_POINTER_ACCEL_PROFILE_DEFAULT: GDesktopPointerAccelProfile = 0;
pub const G_DESKTOP_POINTER_ACCEL_PROFILE_FLAT: GDesktopPointerAccelProfile = 1;
pub const G_DESKTOP_POINTER_ACCEL_PROFILE_ADAPTIVE: GDesktopPointerAccelProfile = 2;

pub type GDesktopProxyMode = c_int;
pub const G_DESKTOP_PROXY_MODE_NONE: GDesktopProxyMode = 0;
pub const G_DESKTOP_PROXY_MODE_MANUAL: GDesktopProxyMode = 1;
pub const G_DESKTOP_PROXY_MODE_AUTO: GDesktopProxyMode = 2;

pub type GDesktopScreensaverMode = c_int;
pub const G_DESKTOP_SCREENSAVER_MODE_BLANK_ONLY: GDesktopScreensaverMode = 0;
pub const G_DESKTOP_SCREENSAVER_MODE_RANDOM: GDesktopScreensaverMode = 1;
pub const G_DESKTOP_SCREENSAVER_MODE_SINGLE: GDesktopScreensaverMode = 2;

pub type GDesktopStylusButtonAction = c_int;
pub const G_DESKTOP_STYLUS_BUTTON_ACTION_DEFAULT: GDesktopStylusButtonAction = 0;
pub const G_DESKTOP_STYLUS_BUTTON_ACTION_MIDDLE: GDesktopStylusButtonAction = 1;
pub const G_DESKTOP_STYLUS_BUTTON_ACTION_RIGHT: GDesktopStylusButtonAction = 2;
pub const G_DESKTOP_STYLUS_BUTTON_ACTION_BACK: GDesktopStylusButtonAction = 3;
pub const G_DESKTOP_STYLUS_BUTTON_ACTION_FORWARD: GDesktopStylusButtonAction = 4;

pub type GDesktopTabletMapping = c_int;
pub const G_DESKTOP_TABLET_MAPPING_ABSOLUTE: GDesktopTabletMapping = 0;
pub const G_DESKTOP_TABLET_MAPPING_RELATIVE: GDesktopTabletMapping = 1;

pub type GDesktopTitlebarAction = c_int;
pub const G_DESKTOP_TITLEBAR_ACTION_TOGGLE_SHADE: GDesktopTitlebarAction = 0;
pub const G_DESKTOP_TITLEBAR_ACTION_TOGGLE_MAXIMIZE: GDesktopTitlebarAction = 1;
pub const G_DESKTOP_TITLEBAR_ACTION_TOGGLE_MAXIMIZE_HORIZONTALLY: GDesktopTitlebarAction = 2;
pub const G_DESKTOP_TITLEBAR_ACTION_TOGGLE_MAXIMIZE_VERTICALLY: GDesktopTitlebarAction = 3;
pub const G_DESKTOP_TITLEBAR_ACTION_MINIMIZE: GDesktopTitlebarAction = 4;
pub const G_DESKTOP_TITLEBAR_ACTION_NONE: GDesktopTitlebarAction = 5;
pub const G_DESKTOP_TITLEBAR_ACTION_LOWER: GDesktopTitlebarAction = 6;
pub const G_DESKTOP_TITLEBAR_ACTION_MENU: GDesktopTitlebarAction = 7;

pub type GDesktopToolbarIconSize = c_int;
pub const G_DESKTOP_TOOLBAR_ICON_SIZE_SMALL: GDesktopToolbarIconSize = 0;
pub const G_DESKTOP_TOOLBAR_ICON_SIZE_LARGE: GDesktopToolbarIconSize = 1;

pub type GDesktopToolbarStyle = c_int;
pub const G_DESKTOP_TOOLBAR_STYLE_BOTH: GDesktopToolbarStyle = 0;
pub const G_DESKTOP_TOOLBAR_STYLE_BOTH_HORIZ: GDesktopToolbarStyle = 1;
pub const G_DESKTOP_TOOLBAR_STYLE_ICONS: GDesktopToolbarStyle = 2;
pub const G_DESKTOP_TOOLBAR_STYLE_TEXT: GDesktopToolbarStyle = 3;

pub type GDesktopTouchpadClickMethod = c_int;
pub const G_DESKTOP_TOUCHPAD_CLICK_METHOD_DEFAULT: GDesktopTouchpadClickMethod = 0;
pub const G_DESKTOP_TOUCHPAD_CLICK_METHOD_NONE: GDesktopTouchpadClickMethod = 1;
pub const G_DESKTOP_TOUCHPAD_CLICK_METHOD_AREAS: GDesktopTouchpadClickMethod = 2;
pub const G_DESKTOP_TOUCHPAD_CLICK_METHOD_FINGERS: GDesktopTouchpadClickMethod = 3;

pub type GDesktopTouchpadHandedness = c_int;
pub const G_DESKTOP_TOUCHPAD_HANDEDNESS_RIGHT: GDesktopTouchpadHandedness = 0;
pub const G_DESKTOP_TOUCHPAD_HANDEDNESS_LEFT: GDesktopTouchpadHandedness = 1;
pub const G_DESKTOP_TOUCHPAD_HANDEDNESS_MOUSE: GDesktopTouchpadHandedness = 2;

pub type GDesktopTouchpadTapButtonMap = c_int;
pub const G_DESKTOP_TOUCHPAD_BUTTON_TAP_MAP_DEFAULT: GDesktopTouchpadTapButtonMap = 0;
pub const G_DESKTOP_TOUCHPAD_BUTTON_TAP_MAP_LRM: GDesktopTouchpadTapButtonMap = 1;
pub const G_DESKTOP_TOUCHPAD_BUTTON_TAP_MAP_LMR: GDesktopTouchpadTapButtonMap = 2;

pub type GDesktopUsbProtection = c_int;
pub const G_DESKTOP_USB_PROTECTION_LOCKSCREEN: GDesktopUsbProtection = 0;
pub const G_DESKTOP_USB_PROTECTION_ALWAYS: GDesktopUsbProtection = 1;

pub type GDesktopVisualBellType = c_int;
pub const G_DESKTOP_VISUAL_BELL_FULLSCREEN_FLASH: GDesktopVisualBellType = 0;
pub const G_DESKTOP_VISUAL_BELL_FRAME_FLASH: GDesktopVisualBellType = 1;

extern "C" {

}
