// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from gir-files (https://github.com/gtk-rs/gir-files.git @ 8e47c67)
// from mutter-gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "Atom", sizeof(Atom), alignof(Atom));
    printf("%s;%zu;%zu\n", "Colormap", sizeof(Colormap), alignof(Colormap));
    printf("%s;%zu;%zu\n", "Cursor", sizeof(Cursor), alignof(Cursor));
    printf("%s;%zu;%zu\n", "Drawable", sizeof(Drawable), alignof(Drawable));
    printf("%s;%zu;%zu\n", "GC", sizeof(GC), alignof(GC));
    printf("%s;%zu;%zu\n", "KeyCode", sizeof(KeyCode), alignof(KeyCode));
    printf("%s;%zu;%zu\n", "KeySym", sizeof(KeySym), alignof(KeySym));
    printf("%s;%zu;%zu\n", "Picture", sizeof(Picture), alignof(Picture));
    printf("%s;%zu;%zu\n", "Pixmap", sizeof(Pixmap), alignof(Pixmap));
    printf("%s;%zu;%zu\n", "Time", sizeof(Time), alignof(Time));
    printf("%s;%zu;%zu\n", "VisualID", sizeof(VisualID), alignof(VisualID));
    printf("%s;%zu;%zu\n", "Window", sizeof(Window), alignof(Window));
    printf("%s;%zu;%zu\n", "XID", sizeof(XID), alignof(XID));
    return 0;
}
